#defines:
#  - TIME_PROCESS_DEBUG

sources:
  - ../TimeProcessLib.cpp	
  - source/Automation.cpp
  - source/Curve.cpp
  
includes:
  - "."
  - ".."
  - "includes"
  - "../../library/includes"
  - "../../library/tests"
  
  # to build without having the whole jamoma repository
  - ../../support/jamoma/includes

libraries:
  - FOUNDATION
  - DSP
  - MODULAR
  - ../../library/build/JamomaScore.dylib

# This project is not available for most architectures (cause of the Gecode 64-bit only dependency)
arch: "x86_64"